### ISSUE TITLE
New link 

### ISSUE THREAD

**Issue by Just253** [0x4Hydro/SteamNitroPhishingLinks#1]
Link: discord-nltro.com
Examples of what I saw: https://discord-nltro.com/steam/gift
Image: 
![image](https://user-images.githubusercontent.com/70507145/132238770-e1696fbd-2f00-471c-9443-2a96f4cc5be7.png)

**Comment by Just253** [comment]
Link: discord-airdrop.com
Example I saw: https://discord-airdrop.com/567REIK
Message: 
```
Discord is distributing, discord is nitro, all you need is level 3 in the incentive or link your steam account in the discord, which has 3+ level. Pick it up from the link below.
https://discord-airdrop.com/567REIK
```

**Comment by itayfunes** [comment]
Added. Thanks!
